language: c
dist: trusty
sudo: required
notifications:
  email: false
git:
  submodules: true
  depth: 3

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
      - zip=linux_32
      - bits=32
  - os: linux
    compiler: gcc
    env:
      - zip=linux_64
      - bits=64
  - os: linux
    compiler: clang
    env:
      - zip=linux_32
      - bits=32
  - os: linux
    compiler: clang
    env:
      - zip=linux_64
      - bits=64
  - os: osx
    compiler: gcc
    env:
      - zip=mac_universal
      - bits=universal
  - os: osx
    compiler: clang
    env:
      - zip=mac_universal
      - bits=universal

script:
  - mkdir build && cd build
  - cmake .. -DCONF=$bits
  - cmake --build .

after_success:
  - cd ../
  - mv bin dummies
  - cp LICENSE dummies/license.txt
  - cp README.md dummies/readme.txt
  - zip -r dummies_$zip.zip dummies
