language: c
dist: trusty
sudo: required
notifications:
  email: false
git:
  submodules: true
matrix:
  include:
  - os: linux
    compiler: gcc
    env: release_file='dummies-linux-32'
    install:
    - sudo apt-get install -y gcc-multilib
    - sudo apt-get install -y libc6-dev-i386
    script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_FLAGS=-m32
    - cmake --build . --config Release
  - os: linux
    compiler: gcc
    env: release_file='dummies-linux-64'
    script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_FLAGS=-m64
    - cmake --build . --config Release
  - os: osx
    compiler: clang
    env: release_file='dummies-macos-universal'
    script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --config Release
before_deploy:
- cd $TRAVIS_BUILD_DIR
- cp LICENSE dummies/LICENSE.txt
- cp README.md dummies/README.md
- zip -r $release_file.zip dummies
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: W0MLcGrYz0x9hH+DLBJedGXYbew87rcScmpaqUw37AdlQjA4zSBZmISwWyknSmlva5Si2yVaU4BLIDvSVzsEbRxlOdsedbY0YRtfHeYewF5LopmmU/x1AEl5kR/nKuzmqsyiae1QzfOrC6P7qsk3iVZUHra+cHJMUfW2HGRrlFO3in65nMH0VtUu2PByb7dlJKo3ItTKtgio0YXXR5f7kLsiJiWMGvVtSSC6EBZKi9S2JpwVYU5DERTrI586UPPn4W1zVFCroCsgqQzevuq3ok/a7GmmxKN44uTMywAZV90V/D6WWXiWuwyHsqq9tE6kbK8NROamVwKKfhPHx8RzbTPMa7PzLMQ7v5PHm3BXCu+wERI8VqPc1RzXJeIjT+rQG+7ffxRIF/HOP1msUEJulZtB5T9a5SxZZ1PgWabfXSQY6EXpYjHLoNOtcOvokILtDFoFyl2NHOEc42hLPcV9yUoX37mCEa1BYKPQ8Y6arxgA2MvXWzrxBXa8DLiajtLHyZx/Gkm34xIOm8cl7+rRSInVHTOenxTlwpUOxPE/BOaufYkGd/GXiMmV96CZdX/Cv081FSb1tk0WYkhtSPqRS44ItigTr0IMQ4ag06yDuZd8YgYvRrqwoFb9GkW87rXSPp6MguRe7dbmD07WWp/ndxEa1TU6s0GGevahOzaQIjg=
  file: $release_file.zip
  on:
    repo: pierreguillot/pd.dummies
    tags: true
