
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
        ZIP: spam_win_32
      - CONFIGURATION: Debug
        PLATFORM: x64
        ZIP: spam_win_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - git clone -q --branch=master https://github.com/pierreguillot/pdwinlib.git
    - cd pdwinlib
    - dir /s /b /o:gn
    - cd ..\

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
    - cmake --build .
